server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://book-db:3306/books
    username: bookuser
    password: bookpass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka