server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://borrow-db:3306/borrows
    username: borrowuser
    password: borrowpass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka