server:
  port: 8083

spring:
  application:
    name: borrow-service

  datasource:
    url: jdbc:mariadb://localhost:3309/borrows
    username: borrowuser
    password: borrowpass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka