server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: borrow-service
          uri: lb://borrow-service
          predicates:
            - Path=/borrowings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"