server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://user-db:3306/borrowed_books
    username: useruser
    password: userpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # http://eureka-server:8761/eureka