server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/books
    username: bookuser
    password: bookpass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka