spring:
  application:
    name: book-service

  cloud:
    config:
      name: book-service

  config:
    import: configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/