server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/michael/Workspace/Bibliothek/ConfigServer/src/main/resources/config
          label: main
  profiles:
    active: native

logging:
  level:
    org.springframework.cloud.config: DEBUG