server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mariadb://localhost:3307/users
    username: useruser
    password: userpass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka