server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:/config-repo

# ... BUT THIS DOESN'T WORK?
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    org.springframework.cloud.config: DEBUG